// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Demo.Message {

  /// <summary>Holder for reflection information generated from service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1zZXJ2aWNlLnByb3RvEgxEZW1vLk1lc3NhZ2UaDW1lc3NhZ2UucHJvdG8y",
            "lAEKC0RlbW9TZXJ2aWNlEkAKA1NheRIZLkRlbW8uTWVzc2FnZS5HcmVldGlu",
            "Z01zZxoeLkRlbW8uTWVzc2FnZS5HcmVldGluZ1Jlc3BvbnNlEkMKDVRlc3RX",
            "aXRoRW1wdHkSFi5EZW1vLk1lc3NhZ2UuRW1wdHlNc2caGi5EZW1vLk1lc3Nh",
            "Z2UuVGVzdFJlc3BvbnNlQg+qAgxEZW1vLk1lc3NhZ2ViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Demo.Message.MessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
